blank_issues_enabled: false
contact_links:
  - name: Get Help
    url: https://github.com/artstio/artst/discussions/new?category=q-a
    about:
      If you can't get something to work the way you expect, open a question in
      the Artst discussions.
  - name: Feature Request
    url: https://github.com/artstio/artst/discussions/new?category=ideas
    about:
      We appreciate you taking the time to improve Artst with your ideas, but we
      use the Artst Discussions for this instead of the issues tab ğŸ™‚.
  # - name: ğŸ’¬ Artst Discord Channel
  #   url: https://artst.link/discord
  #   about: Interact with other people using Artst ğŸ’¿
  - name: ğŸ’¬ New Updates (Twitter)
    url: https://twitter.com/artst
    about: Stay up to date with Remix news on twitter
  - name: ğŸ¿ Artst YouTube Channel
    url: https://artst.link/youtube
    about: Are you a tech lead or wanting to learn more about Remix in depth? Checkout the Remix YouTube Channel
